# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dennis Soemers Homepage
email: d.soemers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal webpage of Dennis Soemers (currently working towards a Ph.D. in Artificial Intelligence at the Vrije Universiteit Brussel).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dennissoemers.github.io" # the base hostname & protocol for your site
twitter_username: DennisSoemers
github_username:  DennisSoemers
linkedin_username:   dennis-soemers
repository: DennisSoemers/DennisSoemers.github.io
author: DennisSoemers
twitter:
  username: DennisSoemers
# TODO can add a logo if I ever have a logo :D
#logo: /assets/my-logo.png
social:
  name: Dennis Soemers
  links:
    - https://twitter.com/DennisSoemers
    - https://github.com/DennisSoemers/
    - https://www.linkedin.com/in/dennis-soemers/

collections:
  projects:
    output: true
    permalink: /projects/:path/
    
plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
theme: minima
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
# Google services
google_analytics: UA-83213872-1